[project]
name = "netpulse"
version = "0.1.0"
description = "Network traffic analysis web application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.6",
    "networkx>=3.4.2",
    "scapy>=2.6.1",
    "uvicorn>=0.34.0",
    "websockets>=14.1",
]
